### ISSUE TITLE
Reviewer 2: Comment 13 & Comment 15: Explain Validation

### ISSUE THREAD

**Issue by katyhuff** [cyclus/fundamentals-paper#127]
> page 23: "However, such exercises are more likely to bring into relief the differences between the modeling paradigms than supply substantial QA and validation.": Right, the QA and validation should be done prior to that exercise. How? This should be better illustrated.

> page 23: "Taken together and strictly adhered to, they present a fortress to protect against poorly designed or otherwise undesirable code. », it would be nice to know what is sufficient for validating a software.

- [x] Note that this comment is somewhat in conflict with other comments made by the same reviewer (concerning shortening discussion of the software.) 
- [x] Is it possible to flesh out this statement with a reference to QA and validation where it is discussed elsewhere?

Other solutions to this comment are welcome. I'm not sure how to satisfy this one without submitting an entire article on methodologies for validation techniques in simulation science. . . based mostly on the section of this paper in question....

**Comment by gidden** [comment]
We should maybe remove the `However, such exercises are more likely to bring into relief the differences between
the modeling paradigms than supply substantial QA and validation.` sentence. We should frame validation in terms of the simulation platform, not the physics, which is what I believe this reviewer wants. The best "validation" we have is the Lotka-Volterra simulations. 

I think explicitly saying that V&V for a simulation kernel is a different exercise than V&V for a physics code may be needed. We can then highlight that because of our separability, physics-based V&V concerns can be addressed explicitly and separately.
