### ISSUE TITLE
Reviewer 2: Comment 18: Lack of "Validation Chapter"

### ISSUE THREAD

**Issue by katyhuff** [cyclus/fundamentals-paper#130]
> The article lacks a chapter on the validation of the models used and a validation of the physics is missing, something the authors are recognizing.

- [ ] It should be made clear in both the paper and the response that the limited physics in these models rely on recipes generated by origen, etc. and should be 
- [ ] A section on validation of modes (cycamore etc) can certainly be added. 
- [ ] Such a section should say nothing more than the fact that the cycamore modules rely primarily on validated input data (recipes) and that validation of externally contributed models is the responsibility of the developer, outside of the scope of this paper.

**Comment by gidden** [comment]
We could add a note about the basic dynamics validation of the kernel via lotka-volterra simulations. I do think that minimal detail is needed here because the "validation" the reviewer wants is very likely in the archetypes. Perhaps we can talk about decay validation via Pyne? (Is Pyne's decay V&V compliant? The functionality cyclus depends on is autogenerated...)

**Comment by katyhuff** [comment]
Closed with 80f0627.
