### ISSUE TITLE
Organization of Demonstration vs Methods

### ISSUE THREAD

**Issue by mbmcgarry** [cyclus/fundamentals-paper#63]
I think that the entire ecosystem section of Demonstration more properly belongs with the Cyclus tools introduced in Methodology (RIF, Resources +Mat, Toolkit, Cycamore), because you're really highlighting non-kernal capabilities in both areas. Perhaps they belong in a separate section all together?  But they  don't seem to flow well in 'Demonstration'.

**Comment by katyhuff** [comment]
I totally see what you're saying here. However, I think there moving the section might not do exactly what I want. I think maybe some more clarifying motivational sentences will help to tie it into the demonstration section. 

Here's what I mean:
What we're really trying to highlight here is that the community-contribution model is working. I put this ecosystem section in demonstration because the emergence of these complementary tools are a demonstration of the success of our plug-in architecture and community-driven development paradigm. 

Sooo... maybe if I add some sentences to that effect at the beginnning and end of that section... it would do the right thing. What do you think @mbmcgarry ?

**Comment by mbmcgarry** [comment]
I think that your suggested clarification would really help tie the section together.  Sounds like a good approach.

**Comment by katyhuff** [comment]
Fixed with #71
